name: machineLearning
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - streamlit
  - pip:
      - audioread==3.0.1
      - cffi==1.17.1
      - decorator==5.2.1
      - dotenv==0.9.9
      - filelock==3.18.0
      - fsspec==2025.5.1
      - git-filter-repo==2.47.0
      - joblib==1.5.1
      - lazy-loader==0.4
      - librosa==0.11.0
      - llvmlite==0.44.0
      - mpmath==1.3.0
      - msgpack==1.1.1
      - musicbrainzngs==0.7.1
      - networkx==3.5
      - numba==0.61.2
      - platformdirs==4.3.8
      - pooch==1.8.2
      - pycparser==2.22
      - pydub==0.25.1
      - python-dotenv==1.1.0
      - pytube==15.0.0
      - redis==6.2.0
      - soundfile==0.13.1
      - soxr==0.5.0.post1
      - spotipy==2.25.1
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - torch==2.7.1
      - yt-dlp==2025.6.9
